### ISSUE TITLE
Only dialog conversion tool detects nodes in 6.3*, other tools do not seem to work.

### ISSUE THREAD

**Issue by alex-turner** [adobe/aem-modernize-tools#14]
After installing aem-modernize-tools-content-1.0.0.zip locally in both vanilla AEM 6.3 and 6.3.3.3, only the dialog conversion tool is able to recognize the node types of concern. For instance the template conversion tool does not detect cq:template node types at any level of path specificity.

**Comment by venturewise** [comment]
Verifying the same experience also in 6.3.3.5.

**Comment by venturewise** [comment]
@alex-turner did you follow all the steps to configure OSGI?
https://opensource.adobe.com/aem-modernize-tools/pages/configuration/page-structure.html

**Comment by alex-turner** [comment]
Hi Charity,

No, I did not, I was not aware of them.  I will look into it.

Thanks for your help!

Alex

**Comment by venturewise** [comment]
It didn't help us, LOL. However, I'm thinking it is a problem with our customized Column Control. If you are able to get it working for you, go ahead and close this ticket.

**Comment by bstopp** [comment]
I'm a bit confused here - The only tool that will work OOTB without customer specific configurations will be the Dialog Conversion tool.

This is because we provide the configurations as part of the tool - _for Adobe provided dialog widgets_. We wrote the original dialogs, so we know what new versions should be in Coral3, and thus we give you those definitions. If you have custom dialog widgets in ExtJS or Coral2 - you must provide the transformation rule for them to be migrated to Coral3.

One thing to keep in mind - what this toolkit does is make the transformations easier. However, the consumers/customers still need to provide the rules for transformation. Instead of writing code, you only need to configure this suite.

1. [Plan for your modernization](https://opensource.adobe.com/aem-modernize-tools/pages/plan-operate/plan.html)
  a) Identify what you're going to update, and how long it will take, and how you will validate it.
2. [Evaluate your site](https://opensource.adobe.com/aem-modernize-tools/pages/plan-operate/evaluation.html) for determining what transformations you want to create.
3. Create your Editable Templates 
  a) This isn't listed in the docs but maybe it should be. 
  b) For each identified editable template - you need to create it so that the transformation has a target
4. [Configure the tools](https://opensource.adobe.com/aem-modernize-tools/pages/configuration.html)
  a) Create the rules you need to do the actual transforms
5. Run the tools.
6. Validate your updated content.

**Note: these tools modify the content in place - it is a destructive process. Do Not Run In Production without planning and a backup.**
